### PR TITLE
Project as root cleanup

### PR DESCRIPTION
**Pull request by gregbci**
As discussed, I reorganized the repo to function as a contributor project, ie: project-at-root style.

1. Cleaned out Assets/ folder, including SPOEffects (we'll fix later via initiative repo, etc)
1. Moved all tests from Assets/ to Package/com.bci4kids.bciessentials/Tests
1. Updated package dependencies for latest LSL package
1. Readme updated for consumer installation of Bessy into their own Unity project

Test as contributor:
* Using a freshly cloned repo (or run `git clean -fdx` in your repo)
* Open repo using Unity
* Run tests (there is one failing test, we have this in the backlog to fix)

Test as consumer:
* Create a new Unity project
* Follow readme steps to import Bessy into project
* Run the P300 sample

### CODE REVIEW

**Comment by gregbci** [comment]
Adding @mattwehner for visibility

**Review by mattwehner — APPROVED** [review]
Looks good.
@gregbci do Apple silicon instructions in the readme no longer apply?

**Comment by gregbci** [comment]
@mattwehner The special apple instructions aren't needed anymore - LSL4Unity fixed the issue (as of this week).

**Comment by gregbci** [comment]
Merging with main to simplify CI build setup  / macos testing for team

**Pull request merged**
