### PR TITLE
Fix hardcode testing

### PR DESCRIPTION
**Pull request by ekinney-lang**
I still need to test out the new shuffle and algorithm with the actual behavior, but here is the update with the GenerateRNRA_FisherYates.

The tests pass as is, but that doesn't mean they will pass in context of the actual behavior. Those need to be evaluated.

### CODE REVIEW

**Comment by gregbci** [comment]
Looks ok, I hade these tests fail for me.  I ran on a mac, but I can't see that mattering:

* GenerateRNRA_WhenValueRangeEqualsThanArrayLength_ThenReturnsArrayWithAllRangesValuesPresent 
* GenerateRNRA_WhenValueRangeLessThanLength_ThenReturnsArrayWithDuplicates

One nitpick - Try using CollectionAssert.AreEqual() to compare array elements instead of a for loop.  Should be much cleaner.  Note - Assert.AreEqual() will only compare the array references (ie: addresses).

**Comment by ekinney-lang** [comment]
> * GenerateRNRA_WhenValueRangeEqualsThanArrayLength_ThenReturnsArrayWithAllRangesValuesPresent
> 
> * GenerateRNRA_WhenValueRangeLessThanLength_ThenReturnsArrayWithDuplicates

These are expected to fail right now - they are part of the "temp fix" that I have not yet been able to remove, as I haven't written the tests for replacing GenerateRNRA with GenerateRNRA_FisherYates.

Thanks for the info on the CollectionsAssert!

**Comment by ekinney-lang** [comment]
Found issue with broken tests - they assumed we still had an inclusive upper bound, when that fix had to be changed for the moment.
Changed Assert calls to include Collections.Assert where appropriate.

**Comment by gregbci** [comment]
Looks good

**Pull request merged**
